### ISSUE TITLE
Sort of Telnet on 192.168.001.150 possible ?

### ISSUE THREAD

**Issue by 9a4db** [erainstruments/erasynth-docs#1]
ERASynth Command List over COM Port at Baud Rate: 115200 bps
is well documented and fully functional.
Question is: can we use the same or similar way to command ERASynth over the wireless? 
If yes, how?  
(mean without use of WEB GUI/ERASynth Control Panel)

**Comment by berjk** [comment]
ERASynth WEB GUI uses HTTP requests to communicate with ESP8266 and the device. If you use the same structure with other programs (SOAP, ..) you can access to ERASynth remotely. We do not have documentation on this commands but they are all in the index.html file clearly. You can find the html file under the firmware repo (esp8266/data folder)

**Comment by 9a4db** [comment]
Tnx.
*Assuming that you are aware that last ver. of web gui app still have bugs, 
regarding freq setup and tracking range...
