### ISSUE TITLE
Baudrate is not specified in firmware update instructions

### ISSUE THREAD

**Issue by ChuckM** [erainstruments/erasynth-docs#2]
In the documentation for updating the firmware, the document says to "connect with terminal emulator or PC GUI" and type >U. But it does not say at what baud rate to connect to the serial port, or whether or not one would expect to see something echoed back to the PC. 

The loading of the ERASynth.ino file proceeeded correctly but I can't tell if the ESP2866 code does.

**Comment by freeGentle** [comment]
Thank you for your valuable feedback. Additional information has been added to the document.
